[#660] Fixed required Composer version constraint and added a CI job.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -85,3 +85,26 @@ jobs:
 
       - name: Run a single unit test to verify the testing setup
         run: ./vendor/bin/phpunit -c ./web/core ./web/core/modules/user/tests/src/Unit/UserAccessControlHandlerTest.php
+
+  # Using outdated Composer version to test the Composer version constraint.
+  test-composer:
+    runs-on: ubuntu-latest
+
+    steps:
+
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Setup PHP
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: 8.2
+          extensions: gd, pdo_sqlite
+          tools: composer:v2.2
+
+      - name: Show Composer version
+        run: composer --version
+
+      - name: Install dependencies
+        # This command should fail because of the Composer version constraint.
+        run: composer --verbose install && exit 1 || exit 0
